---
- name: Installing apache server
  apt: pkg=apache2 state=present

- name: Enabling apache2 on server reboot
  service:
    name: apache2
    enabled: yes

- name: enable load balancer module
  apache2_module: name=proxy_balancer state=present