---
- name: Set root Password
  debconf:
    name: mysql-community-server
    question: 'mysql-community-server/root-pass'
    value: nitmanu # Set as a variable
    vtype: password


- name: Set root Password Again
  debconf:
    name: mysql-community-server
    question: 'mysql-community-server/re-root-pass'
    value: nitmanu # Set as a variable
    vtype: password

- name: Installing mysql 5.6 server
  apt: pkg=mysql-server-5.6 state=present

- name: Enabling mysql to start at boot
  service:
    name: mysqld
    enabled: yes

- name: Start MySQL
  command: service mysql start