---
- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='password' vtype='password'

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='password' vtype='password'

- name: Installing mysql 5.6 server
  apt: pkg=mysql-server-5.6 state=present

- name: Enabling mysql to start at boot
  service:
    name: mysql
    enabled: yes

- name: Start MySQL
  command: service mysql restart